[project]
name = "2025hacks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "elevenlabs>=2.22.0",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
]
